[workspace]
resolver = "2"
members = [
    "rest-server",
    "storage",
    "storage-pg",
    "tests/setup",
]

[workspace.dependencies]
thiserror = "1.0.40"
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }


futures = "0.3"
async-trait = "0.1"
tokio = { version = "1", features = ["full", "sync", "tracing"] }

sqlx = { version = "0.6.2", features = [ "runtime-actix-native-tls", "postgres", "macros", "uuid", "chrono", "offline" ] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tracing = "0.1"
tracing-actix-web = "0.7"
tracing-subscriber =  { version = "0.3", features = ["env-filter"] }

actix-web = "4.9.0"

# dotenvy
dotenv = "0.15.0"

testcontainers = "0.21"
testcontainers-modules = "0.9"