[workspace]
resolver = "2"
members = [
    "rest-server"
]

[workspace.dependencies]
# Tokio ecosystem
#tokio = { version = "1.39.0", features = ["full", "sync", "tracing"] }


# Database infrastructure
sqlx = { version = "0.6.2", features = [ "runtime-actix-native-tls", "postgres", "macros", "uuid", "chrono", "offline" ] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }


# Serde ecosystem and seryalization tools
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.81"


# Logging
tracing = "0.1.37"
tracing-actix-web = "0.7.2"
tracing-subscriber =  { version = "0.3.16", features = ["env-filter"] }


# HTTP, RPC and Schemas
actix-web = "4.9.0"


# Traits
async-trait = "0.1.66"


# Errors, futures, helpers, tools, time, etc...
thiserror = "1.0.40"
dotenv = "0.15.0"
futures = "0.3.30"

