[rest_server]
port = 8080
host = "127.0.0.1"
log_level = "DEBUG"
base_url = "http://localhost:8080"

[json_rpc_server]
port = 8081
host = "127.0.0.1"
log_level = "DEBUG"

[obj_storage]
endpoint = "http://127.0.0.1:9000"
region = "us-east-1"
access_key_id = "admin"
secret_access_key = "password"
bucket_for_json_metadata = "asset-metadata"
bucket_for_binary_assets = "binary-assets"

[solana]
url = "https://api.devnet.solana.com"

[database]
connection_url = "postgres://postgres:postgres@localhost:5432/spell-wallet"
min_connections = 1
max_connections = 20
log_level = "OFF"

[secrets]
master_mnemonic = { Plain = "" }
rest_api_keys = { Plain = "111:name1;222:name2;333:name3" }

[metrics]
enabled = false