name: REST Server Rust CI

on:
  push:
    branches:
      - main
    paths:
      - 'rest-server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'rest-server/**'

env:
  CARGO_TERM_COLOR: always
  RUST_STABLE_VERSION: "1.79.0"

jobs:
  lint:
    name: Linter and Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Stable Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE_VERSION }}
          components: clippy
          cache: true

      - name: Install Nightly Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          cache: true

      - name: Restore Cargo Cache
        id: cache-cargo
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Append to Cargo.toml
        run: |
          echo "[profile.dev]" >> Cargo.toml
          echo "debug = 0" >> Cargo.toml     

      - name: Set Default Rust Toolchain
        run: |
          rustup show 
          rustup override set ${{ env.RUST_STABLE_VERSION }}

      - name: Run Formatter (fmt)
        run: cargo +nightly fmt -- --check

      # TODO: stabilize codebase and filter out stupid rules, after that turn back on
      # - name: Run Linter (clippy)
      #   run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - name: Save Cargo Cache
        id: cache-cargo-save
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-cargo.outputs.cache-primary-key }}
